/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1602ca8dbf66cbb25dd9b3dd91e4c8a3)
interface Env {
  ASSETS: Fetcher;
  COMMENTS_DB: D1Database;
  TURNSTILE_SECRET_KEY?: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import('./src/worker');
  }
  interface Env {
    ASSETS: Fetcher;
    COMMENTS_DB: D1Database;
    TURNSTILE_SECRET_KEY?: string;
  }
}
