/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 1602ca8dbf66cbb25dd9b3dd91e4c8a3)
interface __BaseEnv_Env {
	COMMENTS_DB: D1Database;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
